- name: Remove localization packages that I don't use
  become: true
  ansible.builtin.apt:
    state: absent
    # These are auto-installed as recommended packages on my debian installation
    # and I don't need them.
    purge: true
    name:
      - fbterm
      - nkf
      - task-amharic
      - task-arabic
      - task-asturian
      - task-basque
      - task-belarusian
      - task-bengali
      - task-bosnian
      - task-brazilian-portuguese
      - task-bulgarian
      - task-catalan
      - task-chinese-s
      - task-chinese-t
      - task-croatian
      - task-cyrillic
      - task-czech
      - task-danish
      - task-dutch
      - task-esperanto
      - task-estonian
      - task-finnish
      - task-french
      - task-galician
      - task-german
      - task-greek
      - task-gujarati
      - task-hebrew
      - task-hindi
      - task-hungarian
      - task-icelandic
      - task-irish
      - task-italian
      - task-japanese
      - task-kazakh
      - task-khmer
      - task-korean
      - task-kurdish
      - task-latvian
      - task-lithuanian
      - task-macedonian
      - task-malayalam
      - task-marathi
      - task-northern-sami
      - task-norwegian
      - task-persian
      - task-polish
      - task-portuguese
      - task-punjabi
      - task-romanian
      - task-russian
      - task-serbian
      - task-slovak
      - task-slovenian
      - task-swedish
      - task-tagalog
      - task-tamil
      - task-telugu
      - task-thai
      - task-turkish
      - task-ukrainian
      - task-welsh
      - ibrazilian
      - ibulgarian
      - icatalan
      - idanish
      - idutch
      - ifrench-gut
      - ihungarian
      - iitalian
      - ilithuanian
      - ingerman
      - inorwegian
      - ipolish
      - iportuguese
      - irussian
      - iswiss
      - wbrazilian
      - wbulgarian
      - wcatalan
      - wdanish
      - wdutch
      - wfrench
      - witalian
      - wngerman
      - wnorwegian
      - wpolish
      - wportuguese
      - wswedish
      - manpages-ja-dev
      - hunspell-hu # should be removed when removing task-hungarian

      # spelling packages
      - aspell-am
      - aspell-ar-large
      - aspell-ar
      - aspell-bg
      - aspell-ca
      - aspell-cs
      - aspell-cy
      - aspell-da
      - aspell-de
      - aspell-el
      - aspell-eo
      - aspell-et
      - aspell-eu
      - aspell-fa
      - aspell-fr
      - aspell-ga
      - aspell-gl-minimos
      - aspell-he
      - aspell-hr
      - aspell-hu
      - aspell-is
      - aspell-it
      - aspell-kk
      - aspell-ku
      - aspell-lt
      - aspell-lv
      - aspell-nl
      - aspell-no
      - aspell-pl
      - aspell-pt-br
      - aspell-pt-pt
      - aspell-ro
      - aspell-ru
      - aspell-sk
      - aspell-sl
      - aspell-sv
      - aspell-tl
      - aspell-uk

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Make sure spanish and english localization packages are installed.
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - task-spanish
      - ispanish        # spanish spelling
      - wspanish        # spanish dictionary (i.e. /usr/share/dict)
      - aspell-es       # gnu spelling for spanish
      - task-english
      - ienglish-common # english spelling
      - iamerican       # american english spelling
      - wamerican       # american english dictionary - /usr/share/dict/american-english
      - aspell-en       # gnu spelling for english
